"""add field slug in MailTemplate

Revision ID: 49dee429367
Revises: 34f15d11d02
Create Date: 2015-08-05 14:23:58.064191

"""

# revision identifiers, used by Alembic.
revision = '49dee429367'
down_revision = '34f15d11d02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailtemplates', sa.Column('slug', sa.String(), nullable=False,
                                             server_default=sa.DefaultClause("0")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailtemplates', 'slug')
    ### end Alembic commands ###
