"""add field deleted, updated_at, user_id in Vacancy

Revision ID: 38331aa4875
Revises: 46f4932e624
Create Date: 2015-08-07 16:37:12.968236

"""

# revision identifiers, used by Alembic.
import datetime

revision = '38331aa4875'
down_revision = '46f4932e624'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import false


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('deleted', sa.Boolean(), nullable=False,
                                         server_default=sa.DefaultClause(false())))
    op.add_column('vacancies', sa.Column('updated_at', sa.DateTime(), nullable=True,
                                         server_default=sa.DefaultClause(str(datetime.datetime.now()))))
    op.add_column('vacancies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'user_id')
    op.drop_column('vacancies', 'updated_at')
    op.drop_column('vacancies', 'deleted')
    ### end Alembic commands ###
