"""new_email_length

Revision ID: 1a02b8af502
Revises: 18d21075187
Create Date: 2015-08-24 00:05:51.496422

"""

# revision identifiers, used by Alembic.
revision = '1a02b8af502'
down_revision = '18d21075187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=320),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    ### end Alembic commands ###
