"""new_conditions_logic
Revision ID: 18d21075187
Revises: ca4cb8bb7b
Create Date: 2015-08-14 15:02:30.883782

"""

# revision identifiers, used by Alembic.
revision = '18d21075187'
down_revision = 'ca4cb8bb7b'

from alembic import op
import sqlalchemy as saco


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'hide', new_column_name='is_hidden')
    op.alter_column('vacancies', 'deleted', new_column_name='is_deleted')



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'is_hidden', new_column_name='hide')
    op.alter_column('vacancies', 'is_deleted', new_column_name='deleted')
    ### end Alembic commands ###
