"""del field "url" from Page, add field "type"

Revision ID: ca4cb8bb7b
Revises: bb087e4e53
Create Date: 2015-08-10 15:25:46.853062

"""

# revision identifiers, used by Alembic.

revision = 'ca4cb8bb7b'
down_revision = 'bb087e4e53'

from alembic import op
import sqlalchemy as sa
from project.lib.orm.types import TypeEnum
from project.models import Page


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('type', TypeEnum(Page.TYPE), nullable=True))
    op.create_unique_constraint('pages_type_key', 'pages', ['type'])
    op.drop_column('pages', 'url')
    op.execute('update pages set type = id')
    op.alter_column('pages', 'type', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('pages_type_key', 'pages', type_='unique')
    op.drop_column('pages', 'type')
    ### end Alembic commands ###
