"""Initial alembic revision

Revision ID: 33ffbd43f2e
Revises: 
Create Date: 2015-07-13 17:38:51.196785

"""

# revision identifiers, used by Alembic.
revision = '33ffbd43f2e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
